#
# Performs CI tests upon pull request
#
language: python
python:
  - "2.7"

git:
  submodules: false

sudo: false
cache:
  directories:
    - "~/.platformio"
  
before_install:
  - git config --global core.sshCommand "ssh -i $HOME/.config/ssh/id_rsa -F /dev/null"
  - git submodule update--init --recursive 

install:
  - pip install -U platformio
  - platformio update

script:
  - pio test -e native && pio run
