#
# Performs CI tests upon pull request
#
arch:
  - arm64

services:
  - docker

before_install:
- docker build . -t cutelabnyc/euro-devkit
- docker run --rm -it cutelabnyc/euro-devkit

script:
- pio run
 