#
# Performs CI tests upon pull request
#
language: python
python:
  - "2.7"

git:
  submodules: false
  
sudo: true
cache:
  directories:
    - "~/.platformio"
  
before_install:
  - sudo git submodule update --init --recursive 

install:
  - pip install -U platformio
  - platformio update

script:
  - pio test -e native && pio run
